apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.statefulSet.name }}-config"
  labels:
    {{- include "db.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.configDb.username | quote }}
  POSTGRES_DB: {{ .Values.configDb.db | quote }}