apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "usersecurity.name" . }}-config
  labels:
    {{- include "usersecurity.labels" . | nindent 4 }}
data:
  DB_HOST_PORT: {{ .Values.config.dbHostPort | quote }}
  DB_USER_NAME: {{ .Values.config.username | quote }}
  SHOW_SQL: {{ .Values.config.showSql | quote }}