apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.statefulSet.name }}-secret"
  labels:
    {{- include "db.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secret.dbPassword | quote }}