apiVersion: v1
kind: Secret
metadata:
  name: {{ include "usersecurity.name" . }}-secret
  labels:
    {{- include "usersecurity.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER_PASSWORD: {{ .Values.secret.dbPassword | quote }}